robo9k/rust-magic

src/lib.rs

Hey Robo9k, hope you don't mind an unsolicited PR on the project. It's been a super easy crate to work with, and I appreciate you putting it out there.
The `AsRef<Path>` trait can be used in place of `Path` for improved ergonomics and flexibility. With `AsRef<Path>`, anything that can be cheaply converted into a `Path` typechecks. Because there is an `impl AsRef<Path> for Path`, this change is completely backwards compatible.

Use `AsRef<Path>` wherever a `Path` was previously used.

---

Cargo.toml

Bump alpha version yet again for #29

Release candidate v0.13

---

src/lib.rs

This additional documentation should help with e.g. #8 and #22

Add more comprehensive crate rustdoc

---

src/lib.rs

This adds some doctest examples of how to use `Cookie.load` which should further help with #22 
It also fixes all functions (`Cookie.check`, `Cookie.compile`, `Cookie.list`, `Cookie.load`) that take `&[AsRef<Path>]` to actually work for multiple filenames.
I tried to come up with a better (compile time) solution to the 0=default,>0=file:name issue, but came up blank.
Something like following pseudo code
```rust
pub enum DatabaseFile {
Default,
File(&[Path]),
}
```
Unfortunately that'd get ugly with `?Sized` and lifetime annotations real quick and users could still pass an empty slice at runtime.
I've considered allowing only one file and requiring multiple calls, but `magic_load` and `magic_load_buffers` are _not_ additive. This means you can have either the default database 
file / your …

Add examples for `Cookie::load`, fix multiple `filenames`

---

.github/workflows/docs.yml

Fix docs CI workflow

---

.github/workflows/deny.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/reuse.yml
.github/workflows/scorecards.yml
deny.toml

Implement GitHub Actions workflows best practices

---

Cargo.toml

* Update `magic-sys` dependency `0.3.0-alpha.3` → `0.3.0`
* Update crate version `0.13.0-alpha.3` → `0.13.0`
* Publish new crate version

Release v0.13.0

---

.reuse/dep5
CONTRIBUTING.md
Cargo.toml
LICENSE
LICENSE.md
LICENSES/Apache-2.0.txt
README.md
src/ffi.rs
src/lib.rs

Relicense as `MIT OR Apache-2.0`

---

Cargo.toml
README.md

Actually update all the Rust version numbers

Fix MSRV and documentation

---

.github/workflows/release.yml

Use the GitHub Action for [release-plz](https://github.com/MarcoIeni/release-plz)
This should automatically create and update a merge request for unreleased changes, which includes a changelog created from conventional commits, see #68 
It will also automatically publish unpublished versions to `crates.io`.
See https://release-plz.ieni.dev/docs/github#example-release-pr-and-release

Use `release-plz` GitHub Action

---

.github/workflows/conventional-commits.yml
.github/workflows/deny.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/release.yml
.github/workflows/reuse.yml
.github/workflows/scorecards.yml

This should help with #50 
- set `egress-policy` to "block" https://docs.stepsecurity.io/harden-runner/how-tos/block-egress-traffic
- disable `sudo` https://docs.stepsecurity.io/harden-runner/how-tos/disable-sudo

Add `step-security/harden-runner` to all CI steps

---

.github/workflows/build.yml

This might speedup the build workflow a bit.

Use `mold` linker in CI

---

README-crate.md
data/tests/db-images-png
src/lib.rs

Add a bit of rustdoc to everything.
Still there's places that could need more.

Add a whole lot of rustdoc

---

examples/file-ish.rs
src/lib.rs

More uniform formatting and small fixes for #125

Make docs more consistent

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/custom-issue.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.reuse/dep5

Initial version, might require more, e.g. links to `CONTRIBUTING`.

Add issue and pull request templates

---

CONTRIBUTING.md

**References**
See #105 
Extend the contributions guide according to GitHub community and OpenSSF best practices.

Extend CONTRIBUTING doc 

---

src/ffi.rs
src/lib.rs

**References**
#121
Improve how the internal cookie pointer wrapper is used.

Refactor internal handling of cookie pointer

---

src/lib.rs

**References**
#121 introduced type state ..
.. but didn't allow recovering the non-faulty consumed cookie on state transition errors.

Allow recovering cookie from state transition errors

---

src/lib.rs

**References**
N/A
Previously one would have to use e.g. a slice with just one element to load a single path as a database. This allows to directly use e.g. a `std::path::Path` with the limitation that it is not and can not be generic over `AsRef`.

Implement `TryFrom` for a few select database path types

---

.github/workflows/release.yml

**References**
https://github.com/MarcoIeni/release-plz-action/pull/85#issuecomment-1745527214
Test unreleased `release-plz-action` which should set Git author to our trusty `arbeitsmaschine[bot]`

Test using `release-plz` with automatic Git author

---

.github/workflows/conventional-commits.yml

**References**
none, general bitrot in this repo
Use the improved `cog check` CI workflow from `magic-sys`, which includes newer dependencies and some best practices

Update conventional commits CI workflow from `magic-sys` repo

---

.github/workflows/release.yml

**References**
https://github.com/robo9k/rust-magic/pull/364#issuecomment-3292244328
Check if just updating `release-plz` binary and action fixes the changelog problem

Update `release-plz` action and pinned version within

---

.github/workflows/zizmor.yml

**References**
none, more guardrails
Add the Zizmor CI workflow from `magic-sys`

Add zizmor CI workflow from `magic-sys` repo

---

.github/workflows/scorecards.yml

**References**
none, general bitrot in this repo
Update the Scorecards CI workflow while also switching from branch to repo protection rules

Update OSFF Scorecards CI workflow

---

.github/workflows/lint.yml
Cargo.lock
Cargo.toml
src/ffi.rs
src/lib.rs

**References**
Close issues: https://github.com/robo9k/rust-magic/issues/404
Upgade `magic-sys`  to v0.4
Deps: https://github.com/robo9k/rust-magic/pull/409

feat(deps) Upgrade `magic-sys` to v0.4
