robo9k/rust-magic

src/lib.rs
This crate failed to build in `rustc 1.10.0-nightly (57ef01513 2016-05-23)` with following errors:
```
$ cargo build
src/lib.rs:160:48: 160:58 error: no method named `to_cstring` found for type `&std::ffi::OsStr` in the current scope
src/lib.rs:160         1 => filenames[0].as_ref().as_os_str().to_cstring().unwrap().as_ptr(),
^~~~~~~~~~
src/lib.rs:219:47: 219:57 error: no method named `to_cstring` found for type `&std::ffi::OsStr` in the current scope
src/lib.rs:219         let f = filename.as_ref().as_os_str().to_cstring().unwrap().as_ptr();
^~~~~~~~~~
error: aborting due to 2 previous errors
error: Could not compile `magic`.
```
This patch is using CString::new instead of to_cstring()
=> Use CString::new instead of to_cstring()

src/lib.rs
I believe this is most correct way to convert a `Path` to `* c_char` and hopefully it will never fail again.
Fixes: #17
=> Fix Path to * c_char conversation once again

Cargo.toml, src/lib.rs
This adds `impl Debug for Cookie` by simply deriving it. I believe this fixes #21 but I don't have a good automated test for it.
Resolves #21
=> Implement `std::fmt::Debug` for `Cookie` struct

src/lib.rs
This adds the [`#[must_use]` attribute](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute) and fixes test code.
Adding the attribute to functions that return `std::result::Result` yields the [Clippy "double_must_use" Lint](https://rust-lang.github.io/rust-clippy/master/index.html#double_must_use) if not accompanied by an additional message.
It's a little weird that only `Cookie.set_flags` returns a `bool` instead of `Result`.
When refactoring error handling in this crate, an `InvalidFlags` error variant or such could be used instead.
=> Add `#[must_use]` attribute

Cargo.toml, README.md, rust-toolchain.toml, src/lib.rs
This adds [rustdoc aliases](https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search) for the FFI names of `magic-sys` so those can be found aswell.
The `#[doc(alias)]` rustdoc feature requires Rust 1.48, thus MSRV had to be bumped.
This can be considered a breaking semver change.
=> Add documentation aliases for search

Cargo.toml, src/lib.rs
This changes the previously rather limited error struct type into something more comprehensive.
* `MagicError` is now a non-exhaustive enum, this is a breaking semver change.
* Dependencies `thiserror` and `errno` were added, but they are not part of the public API.
* `Cookie.error` was removed, this is a breaking semver change.
* `Cookie.set_flags` now returns `Result` (see #33), , this is a breaking semver change.
=> Implement more comprehensive errors

Cargo.toml, LICENSE
This adds a MIT `LICENSE` file again. It was removed in #41 but that broke GitHub's license detection.
=> Add MIT `LICENSE` file for GitHub

.github/workflows/docs.yml
This makes the default `main` branch rustdoc available on GitHub Pages while released versions use [docs.rs](https://docs.rs/magic)
=> Add docs CI workflow that publishes rustdoc using GitHub Pages

README.md
This adds an Open Source Security Foundation (OpenSSF) best practices badge: [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/5709/badge)](https://bestpractices.coreinfrastructure.org/projects/5709)
The overall progress is tracked in #48
=> OpenSSF best practices (badge)

.github/workflows/lint.yml
As noted in https://github.com/robo9k/rust-magic/pull/51#issuecomment-1218343384 `actions-rs/clippy-check` broke, most likely since I can't read properly and added the permissions to the wrong workflow job.
=> Fix permissions for right workflow job

Cargo.toml, src/ffi.rs, src/lib.rs
See https://doc.rust-lang.org/edition-guide/rust-2018/index.html
Rust edition 2018 requires Rust v1.13, current MSRV is v1.48 already.
This should be a semver compatible change.
=> Update to Rust edition 2018

Cargo.toml, src/ffi.rs, src/lib.rs
See #4 
* Removes `magic::version()` as there's no real need for it.
This is a semver breaking change.
* Adds `magic::libmagic_version()`
=> Implement `magic_version()`

README.md, src/lib.rs
This adds some more documentation, especially for `CookieFlags` that the user might be interested in, thus helping #8
=> Improve documentation

src/lib.rs
This adds explanations of use cases where the `magic` crate / `libmagic` is not a good fit.
Could probably go into `README` as well.
=> Add use cases section to README

src/lib.rs
While not strictly related to the safety/security heading only, this seems like the right place to mention that this crate is unofficial.
=> Add affiliation disclaimer

Cargo.toml
Previous released version is v0.13.0
Changes
- #54 
- #56 
- #57 
- #59 
- #63 
- #62 
- #64 
- #65 
Removing [`magic::version()`](https://docs.rs/magic/0.13.0/magic/fn.version.html) is a semver breaking change, thus v0.14
=> Release v0.14.0

.reuse/dep5, CHANGELOG.md
This adds a changelog for all the versions on https://crates.io/crates/magic/versions but without listing any actual changes ("TBD" meaning to be done in e.g. #4).
=> Add CHANGELOG

LICENSE.md
This duplicates the `license` from `Cargo.toml` in the more general `LICENSE.md` for the whole project, not just the crate distribution. The gotcha with third-party files for the source distribution as already explained in the very same file remains.
=> Mention SPDX license identifier

.bumpversion.cfg, .reuse/dep5, CHANGELOG.md
Fix changelog from #72 so that #70 does not add duplicate content.
Remove unused `.bumpversion.cfg` now that `release-plz` is used.
=> Cleanup old release configuration

.github/workflows/conventional-commits.yml
Start using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and enforce it using GitHub Actions CI.
This should also allow better integration with other tooling, e.g. creating changelogs, detecting semver changes, publishing releases.
Commit messages before `v0.14.0` do not comply, but history in the default "main" branch must not be rewritten.
=> Use conventional commits

.github/workflows/docs.yml
This replaces the unmaintained `actions-rs` actions with `dtolnay/rust-toolchain`.
This replaces the `gh-pages` branch with deploying via `actions/deploy-pages`.
=> Update docs CI workflow

.github/workflows/docs.yml
GitHub Pages is picky about file/directory permissions, see https://github.com/actions/upload-pages-artifact/blob/main/README.md#file-permissions
=> Fix docs CI workflow some more

.github/workflows/deny.yml
If limited to certain paths, it (or some of its matrix jobs) can not be used as a required status.
=> Always run `cargo deny` CI workflow

.reuse/dep5, CONTRIBUTING.md, README.md, SECURITY.md
Add a security policy for this repo and thus this crate, as per https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository
GitHub's private vulnerability reporting has been enabled for the repo.
=> Add a security policy

.github/dependabot.yml, .reuse/dep5
This adds GitHub's Dependabot both for automated security and regular version updates.
=> Add Dependabot

.github/dependabot.yml
Seems like autodetection from "recent" commits doesn't quite work.
=> Fix Dependabot configuration for conventional commits

Cargo.toml, src/ffi.rs
This replaces the use of `errno::Errno` with `std::io::Error`, thus removing the need for the `errno` crate dependency.
This is a semver breaking change since `FfiError` and thus `MagicError` now indirectly no longer implement auto traits `UnwindSafe` and `RefUnwindSafe`.
The string representation of those errors might also differ now, but this might not be considered public API.
The `errno` field was not publically exposed otherwise previously (but maybe it should in future releases!).
This does not affect MSRV.
=> Replace `errno` crate dependency with `std::io::Error`

Cargo.toml, src/lib.rs
This upgrades the `bitflags` crate dependency from v1 to v2.
This is a semver breaking change since `CookieFlags::from_bits_unchecked` now no longer exists and we don't provide the fn ourselves for compatibility, see https://github.com/bitflags/bitflags/releases/tag/2.0.0
`CookieFlags` never derived the `serde` traits, so those and the internal representation are not a problem.
=> Upgrade to `bitflags` v2

.github/workflows/docs.yml, Cargo.lock
This way breakage should occur early, e.g. dependency not working on nightly.
#98 "downgraded" `proc-macro2` so the MSRV build passed while the nightly doc build failed lateron.
=> Build docs on pull requests but do not deploy them

.github/workflows/docs.yml
Looks like #99 broke for pull requests, where initially `github.event.after` is empty.
The GitHub docs aren't entirely clear on what `github.sha` is, other than that it depends on the event type.
For pull requests, the `--crate--version` doesn't really matter as we don't actually publish it.
=> Fix docs CI workflow SHA for pull requests

.github/workflows/release.yml, .reuse/dep5, release-plz.toml
This uses a private GitHub App instead of a PAT.
Also add the "release" label to pull requests.
=> Reconfigure `release-plz`

.github/workflows/build.yml
This should, in theory, uncover more test problems than regular `cargo test`.
=> Run tests on nightly with `cargo-careful`

src/lib.rs
This fixes the clippy findings that fail CI
There's probably more in #43
=> Fix clippy findings

.github/workflows/lint.yml, README.md, src/lib.rs
As an extension of #107 also find and fix clippy findings in rustdoc.
Adds unofficial `cargo-rustdoc-clippy` as a CI lint job.
Like before, #43 probably would have more.
=> Fix clippy findings in rustdoc

.github/workflows/build.yml, .github/workflows/conventional-commits.yml, .github/workflows/deny.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/reuse.yml, .github/workflows/scorecards.yml
This should make it more clear and succint what workflow and job was run.
Only run jobs on `push` or `pull_request` events where needed.
=> Refactor CI workflow names and events

README.md, examples/file-ish.rs, src/ffi.rs, src/lib.rs
Partially implements #112 
`CookieDatabaseError` might not be needed if the `foo<P: AsRef<Path>>(&self, filenames: &[P])` were e.g. validated with a `TryInto for DatabaseFilePaths`.
=> Refactor error handling

README.md, examples/file-ish.rs, src/ffi.rs, src/lib.rs
This uses typestate so you can only call `Cookie::file` and `Cookie::buffer` after `Cookie::load`.
This idea initially came up in https://github.com/robo9k/rust-magic/issues/6#issuecomment-293592609
This does not implement a builder for `Cookie`.
=> Use typestate for opened/loaded cookies

README.md, examples/file-ish.rs, src/lib.rs
This implements https://github.com/robo9k/rust-magic/issues/112#issuecomment-1741473208
It does not implement a builder as in #6 but using the default database should now be more obvious.
This should thus help with #22 as well.
=> Introduce `DatabasePaths` for valid filename inputs

README.md, examples/file-ish.rs, src/lib.rs
This implements #114
Everything related to `Cookie` is now in a mod `cookie` (still in `src/lib.rs`) with a top-level re-export of `magic::Cookie`.
This is a semver breaking change, but the required changes are mostly mechanical, e.g.
```diff
- let cookie = magic::Cookie::open(magic::CookieFlags::ERROR)?;
+ let cookie = magic::Cookie::open(magic::cookie::Flags::ERROR)?;
```
=> Move everything `Cookie` into mod `cookie`

.reuse/dep5, Cargo.toml, README-crate.md, README.md, src/lib.rs
Partially implements #106 (no website).
Splits the `rust-magic` project README from the `magic` crate README.
=> Split project/crate README

README.md
This replaces the image source of existing badges with those from `shields.io` and adds some new badges.
=> Use `shields.io` badges in GitHub README

.github/workflows/deny.yml
The `EmbarkStudios/cargo-deny-action` is incredibly slow and takes 4+ minutes for every job.
Using the pre-built binary directly should speed things up.
=> Run `cargo-deny` binary without Docker GHA

.github/workflows/release.yml
Using "stable" `cargo` with cached registry should make this faster aswell.
=> Speedup `release-plz` CI by caching

Cargo.toml
**References**
N/A
Use a precise version for all dependencies, so users end up with the same as in `Cargo.lock`.
This doesn't update the `bitflags` dependency, there's e.g. #156 for that.
=> Use precise version for `bitflags` dependency

.github/workflows/release.yml
**References**
#142 
This switches from a specific revision of `release-plz-action` back to the next regular tagged revision that dependabot can update.
=> Use regular `release-plz-action` version again

.github/workflows/release.yml
**References**
https://github.com/actions/create-github-app-token/releases/tag/v1.5.0
Parameter names change, but values stay the same.
=> Update deprecated parameters for `create-github-app-token` action

.github/workflows/build.yml
**References**
CI fails with "cannot find 'ld'", see https://github.com/RalfJung/cargo-careful/issues/31
Update `cargo-careful` to the latest version, `0.4.2`, that contains the fix.
Long-term this should probably be done indirectly by using a pinned `taiki-e/install-action` and then `cargo-careful@latest`.
=> chore(deps): Bump cargo-careful from 0.4.0 to 0.4.2

.github/workflows/conventional-commits.yml
**References**
Current workflow hits the following error:
```
ambiguous SHA1 prefix - found multiple offsets for pack entry; class=Odb (9); code=Ambiguous (-5)
```
This was fixed in cocogitto v6
Bump cocogitto version so conventional commits CI workflow works again.
=> chore(deps): Bump cocogitto from 5.5.0 to 6.2.0

.github/workflows/build.yml
**References**
Current workflow fails with error:
```
Preparing a careful sysroot (target: x86_64-unknown-linux-gnu)... thread 'main' panicked at src/main.rs:267:10:
failed to build sysroot; run `cargo careful setup` to see what went wrong: failed to copy lockfile from sysroot source
```
This was fixed in cargo-careful v0.4.3
Bump cargo-careful version so careful CI workflow works again.
=> chore(deps): Bump cargo-careful from 0.4.2 to 0.4.3

src/lib.rs
**References**
The similar `file_type` crate added benchmarks against `magic` and a link in https://github.com/theseus-rs/file-type/issues/71 so this returns the favor.
Extend existing list of use cases in crate doc with link to alternative pure Rust crate
=> Link to alternative pure Rust crate

.github/workflows/deny.yml, deny.toml
**References**
none, general bitrot in this repo
Use the improved `cargo deny` CI workflow from `magic-sys`, which includes newer dependencies and some but not all best practices
=> Update `cargo deny` CI workflow from `magic-sys` repo

README.md
**References**
none
Given recent activity and the intended feature/fixes queue, the crate is once again maintained (in `$CURRENT_YEAR`)
=> Update maintenance status for current year 2025

.github/renovate.json5
**References**
https://github.com/robo9k/rust-magic/issues/395#issue-3435425922
Use "chore" instead of "fix" semantic commit type for lockfile updates
=> Use `chore` semantic commit type for lockfile updates

README-crate.md, src/lib.rs
**References**
https://github.com/robo9k/rust-magic/issues/404#issuecomment-3356984052
Document the crate features for `libmagic` versions that were added in #410 and used in e.g. #412
=> Document `libmagic` version crate features
